//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Card
{
    public Card()
    {
        this.DealerMoves = new HashSet<DealerMove>();
        this.Hands = new HashSet<Hand>();
        this.Moves = new HashSet<Move>();
        this.Games = new HashSet<Game>();
    }

    public int CardId { get; set; }
    public Nullable<int> CardInfoId { get; set; }
    public Nullable<int> Deck { get; set; }
    public Nullable<bool> IsAvailable { get; set; }

    public virtual CardInfo CardInfo { get; set; }
    public virtual ICollection<DealerMove> DealerMoves { get; set; }
    public virtual ICollection<Hand> Hands { get; set; }
    public virtual ICollection<Move> Moves { get; set; }
    public virtual ICollection<Game> Games { get; set; }
}

public partial class CardInfo
{
    public CardInfo()
    {
        this.Cards = new HashSet<Card>();
    }

    public int CardInfoId { get; set; }
    public Nullable<int> PokerOrder { get; set; }
    public string Name { get; set; }
    public string Image { get; set; }

    public virtual ICollection<Card> Cards { get; set; }
}

public partial class DealerMove
{
    public int MoveId { get; set; }
    public Nullable<int> GameId { get; set; }
    public string PlayType { get; set; }
    public Nullable<int> CardId { get; set; }
    public Nullable<int> Points { get; set; }

    public virtual Card Card { get; set; }
    public virtual Game Game { get; set; }
}

public partial class Game
{
    public Game()
    {
        this.DealerMoves = new HashSet<DealerMove>();
        this.Hands = new HashSet<Hand>();
        this.Moves = new HashSet<Move>();
        this.Turns = new HashSet<Turn>();
        this.Cards = new HashSet<Card>();
        this.Users = new HashSet<Users>();
    }

    public int GameId { get; set; }
    public bool GameState { get; set; }
    public Nullable<int> PlayerCount { get; set; }

    public virtual ICollection<DealerMove> DealerMoves { get; set; }
    public virtual ICollection<Hand> Hands { get; set; }
    public virtual ICollection<Move> Moves { get; set; }
    public virtual ICollection<Turn> Turns { get; set; }
    public virtual ICollection<Card> Cards { get; set; }
    public virtual ICollection<Users> Users { get; set; }
}

public partial class Hand
{
    public int GameId { get; set; }
    public int UserId { get; set; }
    public int CardId { get; set; }

    public virtual Card Card { get; set; }
    public virtual Game Game { get; set; }
    public virtual Users User { get; set; }
}

public partial class Move
{
    public int MoveId { get; set; }
    public Nullable<int> GameId { get; set; }
    public Nullable<int> UserId { get; set; }
    public string PlayType { get; set; }
    public Nullable<int> CardId { get; set; }
    public Nullable<int> Points { get; set; }

    public virtual Card Card { get; set; }
    public virtual Game Game { get; set; }
    public virtual Users User { get; set; }
}

public partial class Record
{
    public int UserId { get; set; }
    public Nullable<int> Wins { get; set; }
    public Nullable<int> Losses { get; set; }
    public Nullable<int> Draws { get; set; }

    public virtual Users User { get; set; }
}

public partial class Turn
{
    public int GameId { get; set; }
    public int UserId { get; set; }
    public Nullable<int> TurnOver { get; set; }

    public virtual Game Game { get; set; }
    public virtual Users User { get; set; }
}

public partial class Users
{
    public Users()
    {
        this.Hands = new HashSet<Hand>();
        this.Moves = new HashSet<Move>();
        this.Turns = new HashSet<Turn>();
        this.Games = new HashSet<Game>();
    }

    public int UserId { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public Nullable<decimal> Money { get; set; }
    public Nullable<int> Wins { get; set; }
    public Nullable<int> Losses { get; set; }
    public int Draws { get; set; }

    public virtual ICollection<Hand> Hands { get; set; }
    public virtual ICollection<Move> Moves { get; set; }
    public virtual Record Record { get; set; }
    public virtual ICollection<Turn> Turns { get; set; }
    public virtual ICollection<Game> Games { get; set; }
}
